version: '3'

volumes:
  data:

services: 
  database:
    image: postgres:11
    ports: 
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./database:/database
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql